# Generated by Django 2.2.4 on 2019-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuiz',
        ),
    ]
