# Generated by Django 2.2.4 on 2019-08-23 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('option_1', models.TextField(blank=True, null=True)),
                ('option_1_chosen', models.IntegerField()),
                ('option_2', models.TextField(blank=True, null=True)),
                ('option_2_chosen', models.IntegerField()),
                ('option_3', models.TextField(blank=True, null=True)),
                ('option_3_chosen', models.IntegerField()),
                ('correct_option', models.CharField(choices=[('a', models.TextField(blank=True, null=True)), ('b', models.TextField(blank=True, null=True)), ('c', models.TextField(blank=True, null=True))], default=models.TextField(blank=True, null=True), max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_answer', models.IntegerField(choices=[(1, 'option_1'), (2, 'option_2'), (3, 'option_3')], default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quiz'),
        ),
    ]
